drop table if exists "user";
create table "user" (
                        "user_id" bigint not null,
                        "created_at" timestamp,
                        "modified_at" timestamp,
                        "email" varchar(255) not null,
                        "nickname" varchar(255) not null,
                        "password" varchar(255) not null,
                        "phone" integer not null,
                        "username" varchar(255) not null, primary key ("user_id"));

drop table if exists "refresh_token";
create table "refresh_token" (
                                 "id" bigint generated by default as identity,
                                 "access_token" varchar(255) not null,
                                 "refresh_token" varchar(255) not null,
                                 primary key ("id"));

drop table if exists "address";
create table "address" (
    "address_id" bigint not null,
    "address" varchar(255) not null,
    "address_detail" varchar(255) not null,
    "default_address" boolean not null,
    "zonecode" varchar(255) not null,
    "user_id" bigint,
    primary key ("address_id"),
    constraint FK_ADDRESS_USER foreign key ("user_id") references "user");

drop table if exists "category_code";
create table "category_code" (
    "id" bigint not null,
    "code" varchar(255),
    "depth1" varchar(255),
    "depth2" varchar(255),
    "name" varchar(255), primary key ("id"));

drop table if exists product;
create table "product" (
    "product_id" bigint not null,
    "created_at" timestamp,
    "modified_at" timestamp,
    "code" varchar(255) not null,
    "name" varchar(255) not null,
    "price" integer not null,
    "summary" varchar(255) not null,
    "thumb" varchar(255) not null,
    primary key ("product_id"));

drop table if exists "product_detail";
create table "product_detail" (
    "product_id" bigint not null,
    "amount" varchar(255) not null,
    "expired" varchar(255) not null,
    "intro_desc" varchar(255) not null,
    "intro_image" varchar(255) not null,
    "notice" varchar(255) not null,
    "origin" varchar(255) not null,
    "package_type" varchar(255) not null,
    "view_image" varchar(255),
    "view_table" varchar(255),
    "weight" varchar(255) not null,
    primary key ("product_id"));

